### ISSUE TITLE
Metaissue for accumulation experiment mvp

### ISSUE THREAD

**Issue by bruno-f-cruz** [AllenNeuralDynamics/Aind.Behavior.ForceForaging#19]
- [x] Fix feedback in schemas and bonsai (right now not tied to a stimuli)
- [x] Fix spout control/spout available/not available
- [x] Implement load cell calibration from schema

**Comment by rozmar** [comment]
Calibration sets voltages to zero, but not totally.
Script could add the remaining mean value as an offset to the min and maxvalues of the LUT axis so calibration is perfect.
